Fixes #16: Deploy natchet-backend application to GCP
ai-cfia/nachet-backend pull request #35
Opened 2023-11-28 16:54 UTC by redat97

#16 
This old issue was closed by accident so was never merged

2023-11-29 15:12 UTC, rngadam requested changes

2023-11-29 15:12 UTC, rngadam commented on tests/test_azure_storage_api.py
> +
strip whitespaces doesn't seem to be turned on

2023-11-29 23:25 UTC, redat97 commented on tests/test_azure_storage_api.py
> +
maybe because it was from an old commit before I had it turned on? Either way changed

2023-11-30 12:02 UTC, rngadam approved these changes

2023-11-30 12:08 UTC, merged

2023-11-30 12:12 UTC, redat97 commented
I added the pull request trigger lint tests are failing so I will open an issue about that for the devs to fix
https://github.com/ai-cfia/nachet-backend/issues/36