Docker Azure deployment action
ai-cfia/nachet-backend pull request #40
Opened 2023-12-03 21:24 UTC by ThomasCardin

- Closes #39

2023-12-03 21:31 UTC, vivalareda approved these changes
looks good, iirc we fixed the lint-test with William last friday so should pass once that PR is approved

2023-12-05 10:28 UTC, rngadam requested changes

2023-12-05 10:28 UTC, rngadam commented on .github/workflows/azure-deployment.yml
> +    uses: ai-cfia/github-workflows/.github/workflows/workflow-deploy-gcp.yml@main
confsued as to why this is called azure-deployment but uses deploy-gcp?

2023-12-05 13:12 UTC, ThomasCardin commented on .github/workflows/azure-deployment.yml
> +    uses: ai-cfia/github-workflows/.github/workflows/workflow-deploy-gcp.yml@main
Done

2023-12-06 12:01 UTC, rngadam requested changes
rework your commit history to link to issue and provide a meaningful commit message

2023-12-22 14:40 UTC, ThomasCardin commented
> rework your commit history to link to issue and provide a meaningful commit message

For every single commit I make, you want me to link the issue? The PR is already linked to the issue (with the number and the title). When this is merged, the commit displayed on the main branch of this PR will contain the issue number and the title.

2024-01-03 20:11 UTC, ThomasCardin commented
> rework your commit history to link to issue and provide a meaningful commit message

done @rngadam

2024-01-03 20:16 UTC, ThomasCardin commented
@rngadam 

Considering that we frequently switch between cloud accounts (Azure, AWS, GCP), wouldn't it be better to simply push our images to our GitHub in·stead? It would allow us to stop constantly changing our credentials in the github secrets. I could take care of making the changes in the repositories if I have the green light.

2024-01-11 18:33 UTC, rngadam commented
> Considering that we frequently switch between cloud accounts (Azure, AWS, GCP), wouldn't it be better to simply push our images to our GitHub instead? It would allow us to stop constantly changing our credentials in the github secrets. I could take care of making the changes in the repositories if I have the green light.

sound reasonable

2024-01-16 14:16 UTC, ThomasCardin commented
> > Considering that we frequently switch between cloud accounts (Azure, AWS, GCP), wouldn't it be better to simply push our images to our GitHub instead? It would allow us to stop constantly changing our credentials in the github secrets. I could take care of making the changes in the repositories if I have the green light.
> 
> sound reasonable

Ok, then i'm closing this PR since we are now pushing images to the Github container registry (GCR)

2024-01-16 14:16 UTC, closed without merging