issue #29: Tagarno API documentation and
ai-cfia/nachet-backend pull request #54
Opened 2024-01-31 21:54 UTC by MaxenceGui

* Add documentation on Tagarno API objectives
* Add get_picture_details function
* Add manual test

2024-02-04 17:08 UTC, rngadam requested changes

2024-02-04 17:08 UTC, rngadam commented on .vscode/extensions.json
> +}
EOF newline missing!

Please add relevant Github workflows to ensure these issues are caught automatically

https://github.com/ai-cfia/github-workflows/blob/main/.github/workflows/workflow-repo-standards-validation.yml

2024-02-04 17:09 UTC, rngadam commented
Something that occurred to me following our discussions: the properties set in the image from the microscope device when capturing with the microscope and transferring the image are probaly not going to follow when we are capturing from the in-browser image canvas (where the microscope is working as a webcam source).

2024-02-05 14:13 UTC, MaxenceGui commented
@rngadam 

Yes, the webcam component we use in the front end is not capturing any metadata since we only took a screenshot of the canvas. I find this other component ([Expo Camera](https://docs.expo.dev/versions/latest/sdk/camera/)). The component has a function call [takePictureAsync](https://docs.expo.dev/versions/latest/sdk/camera/#takepictureasyncoptions) that can get exif data if the image object record it.

2024-02-06 14:00 UTC, rngadam commented
> Yes, the webcam component we use in the front end is not capturing any metadata since we only took a screenshot of the canvas. I find this other component ([Expo Camera](https://docs.expo.dev/versions/latest/sdk/camera/)). The component has a function call [takePictureAsync](https://docs.expo.dev/versions/latest/sdk/camera/#takepictureasyncoptions) that can get exif data if the image object recorded it.

I'm somewhat skeptical this will work with our microscope and return the manufacturer exif but worth testing!

2024-04-25 15:36 UTC, MaxenceGui commented
## Pull Request Status Update

### Summary

This PR was open to work on the Tagarno API integration into Nachet. As of today (April 25), the AI Lab doesn't have either a microscope or a license for the API. Meaning that the PR is blocked for now.

If the conditions to work on the PR are good again, here is what the dev should know:

- Documentation was started and is located to `/docs/tagarno-api-objective.md`
- Code is located at `/microcscope/microscope_info.py`
- Test is located at `/tests/test_microscope_info.py`

However, there still work to be done, that why the PR is still in draft.

- Unittest needs to be written
- Code for Tagarno's API integration need revisit and work
- Documentation will need to be update as you implement your solution

2025-02-26 17:01 UTC, ChromaticPanic commented
Stale, not planning on implementing

2025-02-26 17:01 UTC, closed without merging