issue 64: Increase MAX_CONTENT_LENGHT
ai-cfia/nachet-backend pull request #66
Opened 2024-03-19 17:10 UTC by MaxenceGui

- [x] Add NACHET_MAX_CONTENT_LENGTH environment variable
- [x] Config the MAX_CONTENT_LENGTH value from the app.
-[x] Update read me to include and explain the new environment variable

2024-03-19 17:34 UTC, SonOfLope requested changes

2024-03-19 17:34 UTC, SonOfLope commented on .env.template
> +NACHET_MAX_CONTENT_LENGHT=
```suggestion
NACHET_MAX_CONTENT_LENGTH=
```

2024-03-19 17:34 UTC, SonOfLope commented on README.md
> +* **NACHET_MAX_CONTENT_LENGHT**: Set the maximum size of the file that can be uploaded to the backend. Need to be the same size as the `proxy body size` variable from DevSecOps.
```suggestion
* **NACHET_MAX_CONTENT_LENGTH**: Set the maximum size of the file that can be uploaded to the backend. Needs to be the same size as the `client_max_body_size` [value](https://github.com/ai-cfia/howard/blob/dedee069f051ba743122084fcb5d5c97c2499359/kubernetes/aks/apps/nachet/base/nachet-ingress.yaml#L13) set from the deployment in Howard.
```

2024-03-19 17:34 UTC, SonOfLope commented on README.md
> +* **NACHET_MAX_CONTENT_LENGHT**: Set the maximum size of the file that can be uploaded to the backend. Need to be the same size as the `proxy body size` variable from DevSecOps.
The hyperlink doesn't seem to work in suggested changes but I updated the variable since it wasn't the right one.

2024-03-19 18:01 UTC, SonOfLope approved these changes

2024-03-25 22:36 UTC, k-allagbe approved these changes

2024-03-28 15:13 UTC, RussellJimmies approved these changes

2024-04-02 18:40 UTC, rngadam requested changes

2024-04-02 18:40 UTC, rngadam commented on app.py
> +app.config["MAX_CONTENT_LENGTH"] = eval(os.getenv("NACHET_MAX_CONTENT_LENGTH"))
don't use eval:

https://www.codiga.io/blog/python-eval/

also here a simple int() to convert from string to int would do?

2024-04-02 20:07 UTC, MaxenceGui commented on app.py
> +app.config["MAX_CONTENT_LENGTH"] = eval(os.getenv("NACHET_MAX_CONTENT_LENGTH"))
Done

2024-04-03 20:06 UTC, rngadam approved these changes

2024-04-03 20:06 UTC, rngadam commented
don't forget to change your description to ```fixes #64```

2024-04-03 20:20 UTC, merged